# -*- coding: utf-8 -*-
"""Hw2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oqv5XB3JW0LvN2tO15pLMp3JE6hIVwLn
"""

import pandas as pd

url = 'https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%81%D0%B5%D0%BB%D0%B5%D0%BD%D0%BD%D1%8F_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8#%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C'

tables = pd.read_html(url)

my_table = tables[12]

"""Вивести перші рядки таблиці за допомогою методу head"""

my_table.head()

"""Визначте кількість рядків та стовпців у датафреймі (атрибут shape)

"""

my_table.shape

"""Замініть у таблиці значення "—" на значення NaN

"""

my_table.replace("—", float("NaN"), inplace=True)

"""Визначте типи всіх стовпців за допомогою dataframe.dtypes

"""

types = my_table.dtypes
types

my_table["2014"] = my_table["2014"].astype(float)
my_table["2019"] = my_table["2019"].astype(float)

"""Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)

"""

for column in my_table.columns:
    missing_percentage = my_table[column].isnull().sum() / my_table.shape[0]
    if missing_percentage:
      print(f"Колонка '{column}': {missing_percentage:.1%}")

"""Видаліть з таблиці дані по всій країні, останній рядок таблиці

"""

my_table = my_table.drop(index=my_table.shape[0]-1)
my_table

"""Замініть відсутні дані в стовпцях середніми значеннями цих стовпців (метод fillna)

"""

my_table = my_table.fillna(value=my_table.mean())
my_table

"""Отримайте список регіонів, де рівень народжуваності у 2019 році був вищим за середній по Україні

"""

avg_birth_rate_2019 = my_table['2019'].mean()
higher_than_avg = my_table[my_table['2019'] > avg_birth_rate_2019]['Регіон'].tolist()
print(higher_than_avg)

"""У якому регіоні була найвища народжуваність у 2014 році?

"""

region_max_births = my_table.nlargest(1, "2014")["Регіон"].values[0]
print(region_max_births)

"""Побудуйте стовпчикову діаграму народжуваності по регіонах у 2019 році

"""

import matplotlib.pyplot as plt
my_table.plot(x='Регіон', y='2019', kind='bar', figsize=(12, 6))
plt.title('Народжуваність по регіонах України у 2019 році')
plt.xlabel('Регіон')
plt.ylabel('Кількість народжених(на 1000 осіб)')
plt.show()